// Created by Crowbar 0.71

$modelname "vuthakral\halo\weapons\c_hum_plasmapistol.mdl"

$bodygroup "pp"
{
	studio "c_hum_plasmapistol.smd"
}


$surfaceprop "weapon"

$contents "solid"

$illumposition -1.268 -15.315 -6.792

$cdmaterials "models\vuthakral\"
$cdmaterials "models\vuthakral\halo\weapons\pp\"
$cdmaterials "models\vuthakral\halo\weapons\"

$attachment "muzzle" "b_gun" 9.5 0 1.86 rotate 0 0 0

$cbox 0 0 0 0 0 0

$bbox -0.283 -9.912 -14.306 30.912 7.377 0.721

$hboxset "default"
$hboxset "default"

$definebone "pedestal" "" 0 0 0 0 89.999982 90.000037 0 0 0 0 0 0
$definebone "base" "pedestal" 0 0 0 0 0 -89.999982 0 0 0 0 0 0
$definebone "r_upperarm" "base" 0 -9.399 0 0 0 0 0 0 0 0 0 0
$definebone "r_forearm" "r_upperarm" 10.258252 0 0 0 0 0 0 0 0 0 0 0
$definebone "r_hand" "r_forearm" 10.886317 0 0 0.534627 1.270992 4.094987 0 0 0 0 0 0
$definebone "l_upperarm" "base" 0 9.399039 0 0 0 0 0 0 0 0 0 0
$definebone "l_forearm" "l_upperarm" 10.250686 0 0 0 0 0 0 0 0 0 0 0
$definebone "l_hand" "l_forearm" 10.893662 0 -0.000001 0 0 0 0 0 0 0 0 0
$definebone "l_pinky_low" "l_hand" 3.24501 0.392602 -1.817072 11.499609 0.510047 0.088694 0 0 0 0 0 0
$definebone "l_pinky_mid" "l_pinky_low" 1.390347 -0.000002 0 0 -2.499987 0 0 0 0 0 0 0
$definebone "l_pinky_tip" "l_pinky_mid" 0.963238 -0.000001 -0.000001 0.000056 -6.999888 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger42" "l_pinky_tip" -0.135166 -0.14992 0.018983 2.174205 -10.817964 -1.594943 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger41" "l_pinky_mid" 0.083754 -0.083877 0.050737 2.495403 -3.812635 -1.021526 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger4" "l_pinky_low" 0.16044 -0.064011 0.130446 3.481694 -1.025193 0.867802 0 0 0 0 0 0
$definebone "l_ring_low" "l_hand" 3.676434 0.640862 -0.889039 4.499438 1.002905 0.061306 0 0 0 0 0 0
$definebone "l_ring_mid" "l_ring_low" 1.733049 -0.000001 -0.000002 0 0 0 0 0 0 0 0 0
$definebone "l_ring_tip" "l_ring_mid" 1.212694 0.000001 -0.000001 0.000057 -12.999957 -0.000057 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger32" "l_ring_tip" -0.100039 -0.25806 0.055865 -4.272489 -1.76431 1.660661 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger31" "l_ring_mid" -0.134174 -0.128624 0.013068 -2.0501 -4.813076 1.039575 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger3" "l_ring_low" 0.059917 -0.116599 -0.002691 -0.586594 -0.447766 1.438926 0 0 0 0 0 0
$definebone "l_thumb_low" "l_hand" 0.853687 -0.404338 1.467987 -36.016472 -18.661981 11.232667 0 0 0 0 0 0
$definebone "l_thumb_mid" "l_thumb_low" 1.550021 -0.000003 -0.000001 6.46417 6.038515 0.682393 0 0 0 0 0 0
$definebone "l_thumb_tip" "l_thumb_mid" 1.099382 0.000001 0.000001 5.000027 0.000057 0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger02" "l_thumb_tip" 0.291389 -0.077076 0.090083 17.844195 -5.417603 -83.968973 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger01" "l_thumb_mid" 0.201796 0.08147 0.108948 2.117824 -7.553306 -84.910337 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger0" "l_thumb_low" -0.034569 0.184258 0.096921 0.333923 -2.630505 -86.646182 0 0 0 0 0 0
$definebone "l_index_low" "l_hand" 3.46558 0.435441 1.515124 -7.99511 2.019677 -0.280979 0 0 0 0 0 0
$definebone "l_index_mid" "l_index_low" 1.703123 0.000002 0 -0.000001 -4.000049 0 0 0 0 0 0 0
$definebone "l_index_tip" "l_index_mid" 1.101938 -0.000001 0 -0.000001 -5.499996 -0.000114 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger12" "l_index_tip" 0.058331 -0.11324 0.05191 2.084877 -4.016495 2.68534 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger11" "l_index_mid" 0.053064 -0.203867 0.075508 1.229625 4.463284 3.073288 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger1" "l_index_low" 0.029737 -0.108094 -0.048504 -4.135954 -3.308717 1.186538 0 0 0 0 0 0
$definebone "l_middle_low" "l_hand" 3.639904 0.721579 0.325856 0 0 0 0 0 0 0 0 0
$definebone "l_middle_mid" "l_middle_low" 1.927462 0.000001 0 0 -2.499987 0 0 0 0 0 0 0
$definebone "l_middle_tip" "l_middle_mid" 1.213575 -0.000004 0 0 -6.000072 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger22" "l_middle_tip" -0.016754 -0.194575 -0.029154 4.074991 -12.154206 3.588263 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger21" "l_middle_mid" -0.024782 -0.070292 0.034934 3.038166 -5.773581 4.340098 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Finger2" "l_middle_low" 0.195572 -0.297732 0.064639 0.989785 7.640392 5.024897 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Hand" "l_hand" -0.027878 0.04381 0.229369 -0.258519 6.320467 0.109034 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Forearm" "l_forearm" -0.001789 0.145366 0.000246 -2.400006 -0.999983 -90.000037 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_UpperArm" "l_upperarm" 0.037918 -0.041827 -0.19382 0.66698 0.21188 -90.000037 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_L_Elbow" "l_upperarm" 0.037918 -0.041827 -0.19382 0.66698 0.21188 -90.000037 0 0 0 0 0 0
$definebone "r_index_low" "r_hand" 3.465466 -0.435421 1.515206 -7.995112 -2.019676 0.28098 0 0 0 0 0 0
$definebone "r_index_mid" "r_index_low" 1.696205 0.000005 -0.000001 0.000001 3.999991 0.000116 0 0 0 0 0 0
$definebone "r_index_tip" "r_index_mid" 1.122782 -0.000002 0.000001 0.000001 5.500053 0.000001 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger12" "r_index_tip" 0.017246 0.051814 0.126019 5.102761 -0.529755 177.469037 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger11" "r_index_mid" 0.035704 0.042535 0.152691 1.389825 0.557146 175.962106 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger1" "r_index_low" 0.015743 0.096725 0.014822 -4.599076 -1.732109 175.881251 0 0 0 0 0 0
$definebone "r_thumb_low" "r_hand" 0.853027 0.400697 1.468595 -36.016472 18.661981 -11.232661 0 0 0 0 0 0
$definebone "r_thumb_mid" "r_thumb_low" 1.508486 0 0 6.469892 -5.535347 -0.62567 0 0 0 0 0 0
$definebone "r_thumb_tip" "r_thumb_mid" 1.081697 0.000002 0.000001 4.999972 -0.000057 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger02" "r_thumb_tip" 0.311094 0.239205 0.20881 15.815585 8.300496 -94.299053 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger01" "r_thumb_mid" 0.220398 0.033886 0.181005 0.004925 9.794306 -93.29867 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger0" "r_thumb_low" -0.033167 -0.127651 0.096673 -1.856041 4.497138 -91.244559 0 0 0 0 0 0
$definebone "r_pinky_low" "r_hand" 3.24468 -0.392569 -1.816949 11.49955 -0.510162 -0.1017 0 0 0 0 0 0
$definebone "r_pinky_mid" "r_pinky_low" 1.384233 -0.000004 -0.000001 0.000057 2.499987 0.000058 0 0 0 0 0 0
$definebone "r_pinky_tip" "r_pinky_mid" 0.949636 0.000002 0 -0.000001 6.999886 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger42" "r_pinky_tip" -0.163933 -0.124973 0.185421 1.620153 1.583599 177.813784 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger41" "r_pinky_mid" 0.075211 -0.198689 0.208448 1.809057 4.300908 175.427644 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger4" "r_pinky_low" 0.155701 -0.173345 0.198709 -0.425079 -0.955178 -172.610751 0 0 0 0 0 0
$definebone "r_middle_low" "r_hand" 3.639862 -0.721509 0.326634 0 0 0 0 0 0 0 0 0
$definebone "r_middle_mid" "r_middle_low" 1.922428 -0.000005 0 0 2.499987 0 0 0 0 0 0 0
$definebone "r_middle_tip" "r_middle_mid" 1.224339 0 0 0 6.000071 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger22" "r_middle_tip" -0.022688 0.118317 0.063371 4.366913 0.602525 172.773091 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger21" "r_middle_mid" -0.012745 0.234735 0.115521 2.471797 -5.674345 172.065647 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger2" "r_middle_low" 0.180307 0.202772 0.137844 0.743814 1.039002 171.293413 0 0 0 0 0 0
$definebone "r_ring_low" "r_hand" 3.676252 -0.641082 -0.887103 4.499952 -1.00004 0.000057 0 0 0 0 0 0
$definebone "r_ring_mid" "r_ring_low" 1.728134 0.000001 -0.000002 0 0 0 0 0 0 0 0 0
$definebone "r_ring_tip" "r_ring_mid" 1.204514 0.000002 0 -0.000001 13.000013 0 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger32" "r_ring_tip" -0.174332 -0.09306 0.176728 -3.938396 0.429603 174.737344 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger31" "r_ring_mid" -0.138151 -0.098207 0.104643 -3.454419 -1.520342 175.73727 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Finger3" "r_ring_low" 0.051413 -0.067677 0.07832 -0.980044 -1.136805 174.911077 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Hand" "r_hand" -0.032093 -0.068389 0.234643 -1.327257 -7.51692 176.37383 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Forearm" "r_forearm" -0.001351 -0.212596 0.000246 -2.400006 0.999983 -90.000207 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_UpperArm" "r_upperarm" 0.037939 0.000134 -0.193786 0.666866 -0.212166 -90.000153 0 0 0 0 0 0
$definebone "ValveBiped.Bip01_R_Elbow" "r_upperarm" 0.037939 0.000134 -0.193786 0.666866 -0.212166 -90.000153 0 0 0 0 0 0
$definebone "b_gun" "r_hand" -20.929976 9.826566 -0.899319 -4.082095 -91.274181 0.625498 0 0 0 0 0 0
$definebone "b_cover" "b_gun" 1.937 0.230354 4.936999 0 0 0 0 0 0 0 0 0
$definebone "b_face" "b_gun" -1.03277 0.23037 4.053206 -40.245186 0.000057 0 0 0 0 0 0 0
$definebone "Container002" "" 0 0 0 0 -89.999982 0 0 0 0 0 0 0

$bonemerge "pedestal"
$bonemerge "base"
$bonemerge "r_upperarm"
$bonemerge "r_forearm"
$bonemerge "r_hand"
$bonemerge "l_upperarm"
$bonemerge "l_forearm"
$bonemerge "l_hand"
$bonemerge "l_pinky_low"
$bonemerge "l_pinky_mid"
$bonemerge "l_pinky_tip"
$bonemerge "ValveBiped.Bip01_L_Finger42"
$bonemerge "ValveBiped.Bip01_L_Finger41"
$bonemerge "ValveBiped.Bip01_L_Finger4"
$bonemerge "l_ring_low"
$bonemerge "l_ring_mid"
$bonemerge "l_ring_tip"
$bonemerge "ValveBiped.Bip01_L_Finger32"
$bonemerge "ValveBiped.Bip01_L_Finger31"
$bonemerge "ValveBiped.Bip01_L_Finger3"
$bonemerge "l_thumb_low"
$bonemerge "l_thumb_mid"
$bonemerge "l_thumb_tip"
$bonemerge "ValveBiped.Bip01_L_Finger02"
$bonemerge "ValveBiped.Bip01_L_Finger01"
$bonemerge "ValveBiped.Bip01_L_Finger0"
$bonemerge "l_index_low"
$bonemerge "l_index_mid"
$bonemerge "l_index_tip"
$bonemerge "ValveBiped.Bip01_L_Finger12"
$bonemerge "ValveBiped.Bip01_L_Finger11"
$bonemerge "ValveBiped.Bip01_L_Finger1"
$bonemerge "l_middle_low"
$bonemerge "l_middle_mid"
$bonemerge "l_middle_tip"
$bonemerge "ValveBiped.Bip01_L_Finger22"
$bonemerge "ValveBiped.Bip01_L_Finger21"
$bonemerge "ValveBiped.Bip01_L_Finger2"
$bonemerge "ValveBiped.Bip01_L_Hand"
$bonemerge "ValveBiped.Bip01_L_Forearm"
$bonemerge "ValveBiped.Bip01_L_UpperArm"
$bonemerge "r_index_low"
$bonemerge "r_index_mid"
$bonemerge "r_index_tip"
$bonemerge "ValveBiped.Bip01_R_Finger12"
$bonemerge "ValveBiped.Bip01_R_Finger11"
$bonemerge "ValveBiped.Bip01_R_Finger1"
$bonemerge "r_thumb_low"
$bonemerge "r_thumb_mid"
$bonemerge "r_thumb_tip"
$bonemerge "ValveBiped.Bip01_R_Finger02"
$bonemerge "ValveBiped.Bip01_R_Finger01"
$bonemerge "ValveBiped.Bip01_R_Finger0"
$bonemerge "r_pinky_low"
$bonemerge "r_pinky_mid"
$bonemerge "r_pinky_tip"
$bonemerge "ValveBiped.Bip01_R_Finger42"
$bonemerge "ValveBiped.Bip01_R_Finger41"
$bonemerge "ValveBiped.Bip01_R_Finger4"
$bonemerge "r_middle_low"
$bonemerge "r_middle_mid"
$bonemerge "r_middle_tip"
$bonemerge "ValveBiped.Bip01_R_Finger22"
$bonemerge "ValveBiped.Bip01_R_Finger21"
$bonemerge "ValveBiped.Bip01_R_Finger2"
$bonemerge "r_ring_low"
$bonemerge "r_ring_mid"
$bonemerge "r_ring_tip"
$bonemerge "ValveBiped.Bip01_R_Finger32"
$bonemerge "ValveBiped.Bip01_R_Finger31"
$bonemerge "ValveBiped.Bip01_R_Finger3"
$bonemerge "ValveBiped.Bip01_R_Hand"
$bonemerge "ValveBiped.Bip01_R_Forearm"
$bonemerge "ValveBiped.Bip01_R_UpperArm"


$sectionframes 30 131

$poseparameter "drc_charge" 0 1 loop 0

$weightlist "weights_pp_overcharge_blend" {
	 "pedestal" 0
	 "base" 0
	 "r_upperarm" 1
	 "r_forearm" 1
	 "r_hand" 1
	 "l_upperarm" 1
	 "l_forearm" 1
	 "l_hand" 1
	 "l_pinky_low" 1
	 "l_pinky_mid" 1
	 "l_pinky_tip" 1
	 "ValveBiped.Bip01_L_Finger42" 1
	 "ValveBiped.Bip01_L_Finger41" 1
	 "ValveBiped.Bip01_L_Finger4" 1
	 "l_ring_low" 1
	 "l_ring_mid" 1
	 "l_ring_tip" 1
	 "ValveBiped.Bip01_L_Finger32" 1
	 "ValveBiped.Bip01_L_Finger31" 1
	 "ValveBiped.Bip01_L_Finger3" 1
	 "l_thumb_low" 1
	 "l_thumb_mid" 1
	 "l_thumb_tip" 1
	 "ValveBiped.Bip01_L_Finger02" 1
	 "ValveBiped.Bip01_L_Finger01" 1
	 "ValveBiped.Bip01_L_Finger0" 1
	 "l_index_low" 1
	 "l_index_mid" 1
	 "l_index_tip" 1
	 "ValveBiped.Bip01_L_Finger12" 1
	 "ValveBiped.Bip01_L_Finger11" 1
	 "ValveBiped.Bip01_L_Finger1" 1
	 "l_middle_low" 1
	 "l_middle_mid" 1
	 "l_middle_tip" 1
	 "ValveBiped.Bip01_L_Finger22" 1
	 "ValveBiped.Bip01_L_Finger21" 1
	 "ValveBiped.Bip01_L_Finger2" 1
	 "ValveBiped.Bip01_L_Hand" 1
	 "ValveBiped.Bip01_L_Forearm" 1
	 "ValveBiped.Bip01_L_UpperArm" 1
	 "ValveBiped.Bip01_L_Elbow" 1
	 "r_index_low" 1
	 "r_index_mid" 1
	 "r_index_tip" 1
	 "ValveBiped.Bip01_R_Finger12" 1
	 "ValveBiped.Bip01_R_Finger11" 1
	 "ValveBiped.Bip01_R_Finger1" 1
	 "r_thumb_low" 1
	 "r_thumb_mid" 1
	 "r_thumb_tip" 1
	 "ValveBiped.Bip01_R_Finger02" 1
	 "ValveBiped.Bip01_R_Finger01" 1
	 "ValveBiped.Bip01_R_Finger0" 1
	 "r_pinky_low" 1
	 "r_pinky_mid" 1
	 "r_pinky_tip" 1
	 "ValveBiped.Bip01_R_Finger42" 1
	 "ValveBiped.Bip01_R_Finger41" 1
	 "ValveBiped.Bip01_R_Finger4" 1
	 "r_middle_low" 1
	 "r_middle_mid" 1
	 "r_middle_tip" 1
	 "ValveBiped.Bip01_R_Finger22" 1
	 "ValveBiped.Bip01_R_Finger21" 1
	 "ValveBiped.Bip01_R_Finger2" 1
	 "r_ring_low" 1
	 "r_ring_mid" 1
	 "r_ring_tip" 1
	 "ValveBiped.Bip01_R_Finger32" 1
	 "ValveBiped.Bip01_R_Finger31" 1
	 "ValveBiped.Bip01_R_Finger3" 1
	 "ValveBiped.Bip01_R_Hand" 1
	 "ValveBiped.Bip01_R_Forearm" 1
	 "ValveBiped.Bip01_R_UpperArm" 1
	 "ValveBiped.Bip01_R_Elbow" 1
	 "b_gun" 1
	 "b_cover" 1
	 "b_face" 1
	 "Container002" 0
}

$animation "pp_normal_corrective_animation" "c_hum_plasmapistol_anims\pp_normal_corrective_animation.smd" {
}

$animation "pp_loop_corrective_animation" "c_hum_plasmapistol_anims\pp_loop_corrective_animation.smd" {
}

$animation "pp_normal" "c_hum_plasmapistol_anims\pp_normal.smd" {
	fps 15
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "pp_normal_corrective_animation" 0
	weightlist "weights_pp_overcharge_blend"
}

$animation "pp_loop" "c_hum_plasmapistol_anims\pp_loop.smd" {
	fps 15
	// Crowbar writes this subtract option to prevent jigglebone and poseparameter problems when delta sequences are recompiled.
	subtract "pp_loop_corrective_animation" 0
	weightlist "weights_pp_overcharge_blend"
}

$sequence "idle" {
	"c_hum_plasmapistol_anims\idle.smd"
	activity "ACT_VM_IDLE" 1
	fadein 0.15
	fadeout 0.3
	fps 30
}

$sequence "walk" {
	"c_hum_plasmapistol_anims\walk.smd"
	activity "ACT_WALK" 1
	fadein 0.15
	fadeout 0.15
	fps 30
	loop
}

$sequence "fire_fp" {
	"c_hum_plasmapistol_anims\fire_fp.smd"
	activity "ACT_VM_PRIMARYATTACK" 1
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fire_fp1" {
	"c_hum_plasmapistol_anims\fire_fp1.smd"
	activity "ACT_VM_PRIMARYATTACK" 1
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fire_fp2" {
	"c_hum_plasmapistol_anims\fire_fp2.smd"
	activity "ACT_VM_PRIMARYATTACK" 1
	fadein 0
	fadeout 0
	fps 30
}

$sequence "overheat_start" {
	"c_hum_plasmapistol_anims\overheat_start.smd"
	activity "ACT_SHOTGUN_RELOAD_START" 1
	fadein 0.3
	fadeout 0.3
	fps 30
}

$sequence "overheat_loop" {
	"c_hum_plasmapistol_anims\overheat_loop.smd"
	activity "ACT_VM_RELOAD" 1
	fadein 0.3
	fadeout 0.3
	fps 30
}

$sequence "overheat_finish" {
	"c_hum_plasmapistol_anims\overheat_finish.smd"
	activity "ACT_SHOTGUN_RELOAD_FINISH" 1
	fadein 0.3
	fadeout 0.3
	fps 30
}

$sequence "draw" {
	"c_hum_plasmapistol_anims\draw.smd"
	activity "ACT_VM_DRAW" 1
	{ event AE_CL_PLAYSOUND 0 "drc.pp_ready" }
	fadein 0.3
	fadeout 0.3
	fps 30
}

$sequence "throw_grenade" {
	"c_hum_plasmapistol_anims\throw_grenade.smd"
	activity "ACT_VM_SECONDARYATTACK" 1
	fadein 0.05
	fadeout 0.3
	fps 30
}

$sequence "melee0" {
	"c_hum_plasmapistol_anims\melee0.smd"
	activity "ACT_VM_HITCENTER" 1
	{ event AE_CL_PLAYSOUND 0 "drc.pp_melee0" }
	fadein 0.1
	fadeout 0.3
	fps 30
}

$sequence "melee1" {
	"c_hum_plasmapistol_anims\melee1.smd"
	activity "ACT_VM_HITCENTER" 1
	{ event AE_CL_PLAYSOUND 0 "drc.pp_melee1" }
	fadein 0.1
	fadeout 0.3
	fps 30
}

$sequence "pose1" {
	"c_hum_plasmapistol_anims\pose1.smd"
	activity "ACT_VM_FIDGET" 1
	{ event AE_CL_PLAYSOUND 0 "drc.pp_pose0" }
	fadein 0.3
	fadeout 0.75
	fps 30
}

$sequence "pose2" {
	"c_hum_plasmapistol_anims\pose2.smd"
	activity "ACT_VM_FIDGET" 1
	{ event AE_CL_PLAYSOUND 0 "drc.pp_pose1" }
	fadein 0.3
	fadeout 0.75
	fps 30
}

$sequence "pp_overcharge_blend" {
	"pp_normal"
	"pp_loop"
	autoplay
	blend "drc_charge" 0 1
	blendwidth 2
	delta
	fadein 0.3
	fadeout 0.3
}
